plugin: community.general.proxmox
validate_certs: false
gather_facts: false
user: "{{ lookup('ansible.builtin.env', 'PM_USER') }}"
password: "{{ lookup('ansible.builtin.env', 'PM_PASS') }}"
url: "{{ lookup('ansible.builtin.env', 'TF_VAR_PM_ENDPOINT') }}"
want_facts: true
keyed_groups:
  - key: proxmox_tags_parsed
    separator: ""
    prefix: group
groups:
  tpot: "'tpot' in (proxmox_tags_parsed|list)"
compose:
   ansible_host: proxmox_ipconfig0.ip | default(proxmox_net0.ip) | ansible.utils.ipaddr('address')
   ansible_user: proxmox_ciuser
want_proxmox_nodes_ansible_host: false
